apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-djcf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-djcf
    app.kubernetes.io/part-of: test-app-334
  name: test-component-djcf
  namespace: build-templates-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-djcf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-djcf
    spec:
      containers:
      - image: quay.io/redhat-appstudio/test-images:04fad0a468a848768865434cd3f10dd6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
